ALTER TABLE robots ADD COLUMN position_x DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE robots ADD COLUMN position_y DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE robots ADD COLUMN position_z DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE robots ADD COLUMN yaw_radians DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE robots ADD COLUMN linear_velocity DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE robots ADD COLUMN angular_velocity DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE robots ADD COLUMN motor_current_amp DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE robots ADD COLUMN telemetry_source VARCHAR(50) NOT NULL DEFAULT 'seed';
